[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.36"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
via_ir = true
bytecode_hash = "ipfs"
cbor_metadata = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[profile.default.fuzz]
runs = 1_000
max_test_rejects = 65_536

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 1_000
depth = 128
fail_on_revert = false

[rpc_endpoints]
robinhood_mainnet = "${ROBINHOOD_MAINNET_RPC_URL}"
